version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  order-service:
    build: .
    depends_on:
      - db
    ports:
      - "3003:3003"
    env_file:
      - .env              # Load environment variables from .env file
    volumes:
      - .:/usr/src/app