# === analytics-service/k8s/deployment.yaml ===
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 1754iitmbda/analytics-service:latest
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: CLICKHOUSE_URL
              value: "https://de3td20bxj.ap-south-1.aws.clickhouse.cloud:8443"
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DB
              value: Lugx