apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
stringData:
  CLICKHOUSE_URL: "https://de3td20bxj.ap-south-1.aws.clickhouse.cloud:8443"
  CLICKHOUSE_PASSWORD: "8n.~w5Yzdusuz"
