apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
        - name: game-service
          image: 1754iitmbda/game-service:latest
          imagePullPolicy: Never # Change to IfNotPresent or Always in production
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: game-service-secret
          readinessProbe:
            httpGet:
              path: /api/game
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/game
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: NodePort
  selector:
    app: game-service
  ports:
    - port: 8080            # Internal cluster port
      targetPort: 8080      # Container's port
      nodePort: 30080       # Exposed on host at this port (optional)
