apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=           # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=       # password
  POSTGRES_DB: Z2FtZXNkYg==             # gamesdb (initial DB for PostgreSQL container)
